import type { Application } from '@/types'

/** Demo applications matching the Figma board design */
export const SAMPLE_APPS: Application[] = [
  {
    id: '1',
    company: 'Stripe',
    role: 'Senior Frontend Engineer',
    appliedDate: '2026-07-10',
    jobLink: 'https://stripe.com/jobs',
    notes: 'Referred by a friend at Stripe. Strong culture fit.',
    status: 'applied',
    color: '#635bff',
  },
  {
    id: '2',
    company: 'Vercel',
    role: 'Developer Advocate',
    appliedDate: '2026-07-18',
    jobLink: '',
    notes: '',
    status: 'applied',
    color: '#000',
  },
  {
    id: '3',
    company: 'Google',
    role: 'Software Engineer III',
    appliedDate: '2026-07-05',
    jobLink: 'https://careers.google.com',
    notes: 'Applied via university referral portal.',
    status: 'applied',
    color: '#4285f4',
  },
  {
    id: '4',
    company: 'Goldman Sachs & Co.',
    role: 'Technology Analyst',
    appliedDate: '2026-07-20',
    jobLink: '',
    notes: '',
    status: 'applied',
    color: '#6b5e3a',
  },
  {
    id: '5',
    company: 'Figma',
    role: 'Design Engineer',
    appliedDate: '2026-06-28',
    jobLink: 'https://figma.com/careers',
    notes: 'Second round scheduled for next week. Technical challenge sent.',
    status: 'interview',
    color: '#a259ff',
  },
  {
    id: '6',
    company: 'Notion',
    role: 'Product Manager',
    appliedDate: '2026-07-01',
    jobLink: '',
    notes: 'Phone screen went well. Technical round pending.',
    status: 'interview',
    color: '#374151',
  },
  {
    id: '7',
    company: 'Linear',
    role: 'Growth Engineer',
    appliedDate: '2026-07-12',
    jobLink: '',
    notes: '',
    status: 'interview',
    color: '#5e6ad2',
  },
  {
    id: '8',
    company: 'Airbnb',
    role: 'Senior Product Designer',
    appliedDate: '2026-06-20',
    jobLink: 'https://airbnb.com/careers',
    notes: 'Competitive offer received — evaluating with advisor.',
    status: 'offer',
    color: '#ff385c',
  },
  {
    id: '9',
    company: 'Netflix',
    role: 'Senior Software Engineer',
    appliedDate: '2026-06-15',
    jobLink: '',
    notes: '',
    status: 'rejected',
    color: '#e50914',
  },
  {
    id: '10',
    company: 'Shopify',
    role: 'Staff Engineer',
    appliedDate: '2026-07-08',
    jobLink: '',
    notes: 'Position filled internally.',
    status: 'rejected',
    color: '#5a8a3c',
  },
  {
    id: '11',
    company: 'Meta',
    role: 'Product Engineer, Reels',
    appliedDate: '2026-07-03',
    jobLink: '',
    notes: '',
    status: 'rejected',
    color: '#0866ff',
  },
]
